replicaCount: 1

image:
  repository: quay.io/openware/clearport
  tag: 0.1.7
  pullPolicy: IfNotPresent
  pullSecret: openware-quay

fullnameOverride: ""
nameOverride: ""

secrets: {}
externalSecret: clearport-sec

nodeSelector: {}

tolerations: []

affinity: {}

profile:
  enabled: false
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

probes:
  readiness: {}
  liveness: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

extraLabels: {}
