{{- $users := .Values.users }}
{{- range $clusterRole := .Values.roles.cluster }}

{{- $userNames := list }}
{{- range $user := $users }}
  {{- if has $clusterRole $user.roles }}
  {{- $userNames = append $userNames $user.name }}
  {{- end }}
{{- end }}

{{- if gt (len $userNames) 0 }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s-binding" $clusterRole }}
roleRef:
  kind: ClusterRole
  name: {{ $clusterRole }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  {{- range $userName := $userNames }}
  - kind: User
    name: {{ printf "system:serviceaccount:default:%s" $userName }}
    apiGroup: rbac.authorization.k8s.io
  {{- end }}
{{- end }}
{{- end }}
