{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "component.fullname" . }}-opt-env
  labels:
    {{- include "component.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-1"
data:
{{- range $key, $value := .Values.secrets  }}
  {{- $key | nindent 2 }}: {{ $value | print | b64enc }}
{{- end }}
{{- end }}
