namespaces:
  - ynet-v2-prod
  - terminal-prod
  - kayen-prod
  - core

users:
  - name: phil
    roles:
      - cluster-admin
  - name: ynet-ci
    roles:
      - ynet-v2-prod-admin
  - name: kayen-ci
    roles:
      - terminal-prod-admin
      - kayen-prod-admin
      - svc-reader
  - name: mnaichuk
    roles:
      - terminal-prod-admin
      - kayen-prod-admin
      - cluster-view
  - name: dsteblyna
    roles:
      - kayen-prod-viewer
  - name: maxpushka
    roles:
      - cluster-admin
